- name: ndenv dir check
  tags:
    - anyenv
    - anyenv/ndenv
    - node
  command: test -d {{ ndenv_path }}
  register: ndenv_dir_check
  failed_when: ndenv_dir_check.rc not in [0,1] 

- name: ndenv install
  tags:
    - anyenv
    - anyenv/ndenv
    - node
  when: ndenv_dir_check.rc != 0
  shell: |
    source /etc/profile.d/proglang.sh
    anyenv install ndenv

- name: ndenv releases check
  tags:
    - anyenv
    - anyenv/ndenv
    - node
  shell: |
    source /etc/profile.d/proglang.sh
    ndenv install -l

- name: rewrite node__path
  tags:
    - anyenv
    - anyenv/ndenv
    - node
  set_fact:
    node__bin_path: "{{ ndenv_path }}/shims:{{ ndenv_path }}/bin"
