- name: ndenv dir check
  tags:
    - ndenv
    - node
  command: test -d {{ ndenv_path }}
  register: ndenv_dir_check
  failed_when: ndenv_dir_check.rc not in [0,1] 

- name: ndenv install
  tags:
    - ndenv
    - node
  when: ndenv_dir_check.rc != 0
  shell: |
    source /etc/profile.d/proglang.sh
    anyenv install ndenv 

- name: ndenv releases check
  tags:
    - ndenv
    - node
  shell: |
    source /etc/profile.d/proglang.sh
    ndenv install -l
