- name: IO_SWF source directory check
  command: test -d {{ IO_SWF_path }}
  register: IO_SWF_dir_check
  failed_when: IO_SWF_dir_check.rc not in [0,1]

- name: IO_SWF source directory remove
  when: IO_SWF_dir_check.rc == 0
  file: >
    path={{ IO_SWF_path }}
    state=absent

- name: IO_SWF repository clone
  ignore_errors: yes
  git: >
    repo=https://github.com/openpear/IO_SWF.git
    dest={{ IO_SWF_path }}
    
- name: IO_SWF files set on php directory
  shell: |
    cp -R {{ IO_SWF_path }}/* {{ installed_php_dir }}/lib/php/
