- name: MySQL repo file check
  tags:
    - mysql
  command: test -f /etc/yum.repos.d/mysql-community.repo
  register: mysql_repo_check
  failed_when: mysql_repo_check.rc not in [0,1]

- name: MySQL repo install 
  tags:
    - mysql
  become: true
  when: mysql_repo_check.rc != 0
  yum: >
    name=http://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm
    state=present
