- name: nginx-build package install
  tags:
    - nginx
    - nginx-build
  become: true
  ignore_errors: yes
  shell: |
    source /etc/profile.d/proglang.sh
    go get github.com/cubicdaiya/nginx-build

