- name: elasticsearch install
  tags: 
    - elasticsearch
  ignore_errors: yes
  yum: >
    name=elasticsearch
    state=latest

- name: elasticsearch start
  tags:
    - elasticsearch
  service: >
    name=elasticsearch
    state=restarted
    enabled=yes
