- name: necessaary package for goofys
  tags:
    - golang
    - golang/package/goofys
  become: true
  yum: >
    name=fuse
    state=latest

- name: goofys package install
  tags:
    - golang
    - golang/package/goofys
  ignore_errors: yes
  shell: |
    source /etc/profile.d/proglang.sh
    go get github.com/kahing/goofys
    go install github.com/kahing/goofys
