- name: docker ce install
  tags:
    - docker
  become: true
  ignore_errors: yes
  yum: >
    name=docker-ce
    state=latest
    enablerepo=docker-ce-stable

- name: docker ce start
  tags:
    - docker
  become: true
  service: >
    name=docker
    state=restarted
    enabled=yes
