- name: fluentd forest match config copy
  tags:
    - fluentd
    - fluentd/config/match/forest
  become: true
  template: >
    src=forest.conf.j2
    dest=/etc/td-agent/match.d/forest.{{ item.tag_name }}.conf
    mode=0755
  with_items: "{{ fluentd_config_match_forest_configs }}"
