dependencies:
  - role: common/fluentd/gem
    fluentd_gems: 
      - fluent-plugin-forest
  - role: common/fluentd/config/match/base
    fluentd_config_match_base_configs: "{{ fluentd_config_match_forest_configs }}"
    fluentd_config_match_base_prefix: forest
