- name: fluentd install
  tags:
    - fluentd
  ignore_errors: yes
  yum: >
    name=td-agent
    state=latest 
    enablerepo=treasuredata

- name: create input config directory of fluentd
  tags:
    - fluentd
  file: >
    path=/etc/td-agent/input.d
    state=directory

- name: create filter config directory of fluentd
  tags:
    - fluentd
  file: >
    path=/etc/td-agent/filter.d
    state=directory

- name: create output config directory of fluentd
  tags:
    - fluentd
  file: >
    path=/etc/td-agent/output.d
    state=directory

- name: fluentd include setting check
  tags:
    - fluentd
  command: grep -P '^include' /etc/td-agent/td-agent.conf
  register: fluentd_conf_include_check
  failed_when: fluentd_conf_include_check.rc not in [0,1]

- name: add include setting to fluentd conf
  tags:
    - fluentd
  when: fluentd_conf_include_check.rc != 0
  shell: |
    echo "" >> /etc/td-agent/td-agent.conf
    echo "include /etc/td-agent/input.d/*.conf" >> /etc/td-agent/td-agent.conf
    echo "include /etc/td-agent/filter.d/*.conf" >> /etc/td-agent/td-agent.conf
    echo "include /etc/td-agent/output.d/*.conf" >> /etc/td-agent/td-agent.conf

- name: fluentd service enable 
  tags:
    - fluentd
  when: service_enable == 1
  service: >
    name=td-agent
    enabled=yes

- name: fluentd restart
  tags:
    - fluentd
  when: service_enable == 1
  service: >
    name=td-agent
    state=started

