- name: fluentd install
  tags:
    - fluentd
  ignore_errors: yes
  yum: >
    name=td-agent
    state=latest 
    enablerepo=treasuredata

- name: fluentd service enable 
  tags:
    - fluentd
  service: >
    name=td-agent
    enabled=yes

# conf作成してからstartした方がよさそう
- name: fluentd restart
  tags:
    - fluentd
  when: ansible_virtualization_type != 'docker'
  service: >
    name=td-agent
    state=started
