- name: fluentd install
  tags:
    - fluentd
  ignore_errors: yes
  yum: >
    name=td-agent
    state=latest 
    enablerepo=treasuredata

- name: create input config directory of fluentd
  tags:
    - fluentd
  file: >
    path=/etc/td-agent/input.d
    state=directory

- name: create filter config directory of fluentd
  tags:
    - fluentd
  file: >
    path=/etc/td-agent/filter.d
    state=directory

- name: create output config directory of fluentd
  tags:
    - fluentd
  file: >
    path=/etc/td-agent/output.d
    state=directory

- name: fluentd include setting check
  tags:
    - fluentd
  command: grep -P '^@include' /etc/td-agent/td-agent.conf
  register: fluentd_conf_include_check
  failed_when: fluentd_conf_include_check.rc not in [0,1]

- name: backup original fluentd config file
  tags:
    - fluentd
  when: fluentd_conf_include_check.rc != 0
  command: cp /etc/td-agent/td-agent.conf /etc/td-agent/td-agent.conf.orig

- name: fluentd config copy
  tags:
    - fluentd
  when: fluentd_conf_include_check.rc != 0
  template: >
    src=td-agent.conf.j2
    dest=/etc/td-agent/td-agent.conf
    mode=0755

- name: fluentd service enable 
  tags:
    - fluentd
  when: service_enable == 1
  service: >
    name=td-agent
    enabled=yes

- name: fluentd restart
  tags:
    - fluentd
  when: service_enable == 1
  service: >
    name=td-agent
    state=started

