- name: fluentd install
  tags:
    - fluentd
  become: true
  ignore_errors: yes
  yum: >
    name=td-agent
    state=latest 
    enablerepo=treasuredata

- name: create config directories of fluentd
  tags:
    - fluentd
  become: true
  file: >
    path=/etc/td-agent/{{ item }}
    state=directory
  with_items:
    - source.d
    - filter.d
    - match.d
    - partial.d

- name: fluentd include setting check
  tags:
    - fluentd
  command: grep -P '^@include' /etc/td-agent/td-agent.conf
  register: fluentd_conf_include_check
  failed_when: fluentd_conf_include_check.rc not in [0,1]

- name: backup original fluentd config file
  tags:
    - fluentd
  become: true
  when: fluentd_conf_include_check.rc != 0
  command: cp /etc/td-agent/td-agent.conf /etc/td-agent/td-agent.conf.orig

- name: fluentd config copy
  tags:
    - fluentd
  become: true
  when: fluentd_conf_include_check.rc != 0
  template: >
    src=td-agent.conf.j2
    dest=/etc/td-agent/td-agent.conf
    mode=0755

- name: fluentd service enable 
  tags:
    - fluentd
  become: true
  when: service_enable == 1
  service: >
    name=td-agent
    enabled=yes

- name: fluentd restart
  tags:
    - fluentd
  become: true
  when: service_enable == 1
  service: >
    name=td-agent
    state=started

