dependencies:
  - role: common/fluentd/gem
    fluentd_gems: 
      - fluent-plugin-elasticsearch
  - role: common/elasticsearch/elasticsearch-defaults
  - role: common/fluentd/config/match/base
    fluentd_config_match_base_configs: "{{ fluentd_config_match_elasticsearch_configs }}"
    fluentd_config_match_base_prefix: elasticsearch
