- name: pj_app directory check
  shell: test -d /product/{{ item }} || mkdir -p /product/{{ item }}
  ignore_errors: true
  with_items: pj_app

- name: pj_app conf directory check
  shell: test -d /etc/httpd/conf.d/{{ pj_name }}/ || mkdir -p /etc/httpd/conf.d/{{ pj_name }}/
  ignore_errors: true

- name: copy Apache VirtualHost config file
  template: >
    src=virtualhost.conf.j2
    dest=/etc/httpd/conf.d/virtualhost.conf

- name: copy Apache pj app config file
  template: >
    src=pj_app.conf.j2
    dest=/etc/httpd/conf.d/{{ pj_name }}/{{ item }}.conf
  with_items: pj_app

- name: copy Apache pj_admin config file
  template: >
    src=pj_admin.conf.j2
    dest=/etc/httpd/conf.d/{{ pj_name }}/{{ pj_name }}_admin.conf

- name: copy Apache pj_media config file
  template: >
    src=pj_media.conf.j2
    dest=/etc/httpd/conf.d/{{ pj_name }}/{{ pj_name }}_media.conf
