- name: nginx depends library install
  tags:
    - nginx
    - nginx/install
  become: true
  ignore_errors: yes
  yum: >
    name={{ item }}
    state=latest
  with_items:
    - libxslt-devel
    - gettext

- name: create nginx-build work directory
  tags:
    - nginx
    - nginx/install
  become: true
  file: >
    path={{ nginx_build_work_directory }}
    state=directory

- name: nginx third party module config copy
  tags:
    - nginx
    - nginx/install
  become: true
  template: >
    src=third_party_modules.j2
    dest={{ nginx_module_file_path }}

- name: nginx configure
  tags:
    - nginx
    - nginx/install
  become: true
  ignore_errors: yes
  shell: |
    source /etc/profile.d/proglang.sh
    export LUAJIT_LIB=/usr/local/lib
    export LUAJIT_INC=/usr/local/include/luajit-2.0
    nginx-build \
      -v {{ nginx_version }} \
      -d {{ nginx_build_work_directory }} \
      -m {{ nginx_module_file_path }} \
      -clear \
      -pcre \
      -zlib \
      -openssl \
      -sbin-path=/usr/sbin/nginx \
      -conf-path=/etc/nginx/nginx.conf \
      -error-log-path={{ nginx__log_dir }}/error.log \
      -http-log-path={{ nginx__log_dir }}/access.log \
      -http-client-body-temp-path=/var/lib/nginx/tmp/client_body \
      -http-proxy-temp-path=/var/lib/nginx/tmp/proxy \
      -http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi \
      -pid-path=/var/run/nginx.pid \
      -lock-path=/var/lock/subsys/nginx.lock \
      -user=nginx \
      -group=nginx \
      -with-debug \
      -with-file-aio \
      -with-pcre-jit \
      -with-http_gzip_static_module \
      -with-http_ssl_module \
      -with-http_stub_status_module \
      -with-http_realip_module \
      -with-http_addition_module \
      -with-http_flv_module \
      -with-http_mp4_module \
      -with-http_secure_link_module \
      -with-http_degradation_module \
      -with-http_xslt_module \
      -with-http_v2_module \
      -with-ld-opt="-Wl,-rpath,/path/to/luajit-or-lua/lib" 

- name: nginx install
  tags:
    - nginx
    - nginx/install
  become: true
  shell: |
     cd {{ nginx_make_work_directory }}
     make install

- name: create nginx conf directories
  tags:
    - nginx
    - nginx/install
  become: true
  file: >
    path={{ item }}
    state=directory
  with_items:
    - /etc/nginx/conf.d
    - /etc/nginx/conf.d/server
    - /etc/nginx/conf.d/upstream
    - /etc/nginx/conf.d/location
    - /etc/nginx/conf.d/location_proxy
    - /etc/nginx/conf.d/lua

- name: create nginx templates directories
  tags:
    - nginx
    - nginx/install
  become: true
  file: >
    path={{ item }}
    state=directory
  with_items:
    - /etc/nginx/templates/server
    - /etc/nginx/templates/upstream
    - /etc/nginx/templates/location
    - /etc/nginx/templates/location_proxy

- name: create nginx data directories
  tags:
    - nginx
    - nginx/install
  become: true
  file: >
    path={{ item }}
    state=directory
    owner={{ nginx__user }}
    group={{ nginx__user }}
  with_items:
    - /var/lib/nginx/tmp
    - /var/cache/nginx

- name: nginx conf files copy
  tags:
    - nginx
    - nginx/install
  become: true
  template: >
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
    mode=0755

- name: nginx sysconfig copy
  tags:
    - nginx
    - nginx/install
  become: true
  template: >
    src=sysconfig.j2
    dest=/etc/sysconfig/nginx

- name: nginx init.d script copy
  tags:
    - nginx
    - nginx/install
  become: true
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'
  template: >
    src=init.d.j2
    dest=/etc/rc.d/init.d/nginx
    mode=0755

- name: nginx systemd service copy
  tags:
    - nginx
    - nginx/install
  become: true
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
  template: >
    src=nginx.service.j2
    dest=/usr/lib/systemd/system/nginx.service
    mode=0644

- name: nginx service enable by RHEL6
  tags:
    - nginx
    - nginx/install
  become: true
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6' and service_enable == 1
  service: >
    name=nginx
    enabled=yes

- name: nginx service enable by RHEL7
  tags:
    - nginx
    - nginx/install
  become: true
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7' and service_enable == 1
  service: >
    name=nginx.service
    enabled=yes
