nginx_config_rewrite_proxy_config_name: config_rewrite_proxy
nginx_config_rewrite_proxy_location: "/{{ nginx_config_rewrite_proxy_config_name }}"
nginx_config_rewrite_proxy_upstream: "upstream_{{ nginx_config_rewrite_proxy_config_name }}"
nginx_config_rewrite_proxy_host: localhost
nginx_config_rewrite_proxy_port: 8080
nginx_config_rewrite_proxy_root: ""
nginx_config_rewrite_proxy_servers:
  - "{{ nginx_config_rewrite_proxy_host }}:{{ nginx_config_rewrite_proxy_port }}" 
