- name: kibana install
  tags: 
    - elasticsearch
    - kibana
  ignore_errors: yes
  yum: >
    name=kibana
    state=latest

- name: kibana start
  tags:
    - kibana
  service: >
    name=kibana
    state=restarted
    enabled=yes
