- name: fluentd record_reformer match config copy
  tags:
    - fluentd
    - fluentd/config/match/record_reformer
  become: true
  template: >
    src=record_reformer.conf.j2
    dest=/etc/td-agent/match.d/record_reformer.{{ item.tag_name }}.conf
    mode=0755
  with_items: "{{ fluentd_config_match_record_reformer_configs }}"
