- name: copy td-agent.conf
  tags:
    - fluentd
  template: >
    src=td-agent.conf.j2
    dest=/etc/td-agent/td-agent.conf

- name: fluentd restart
  tags:
    - fluentd
  service: >
    name=td-agent
    state=started
    enabled=yes
