- name: serverspec gem install
  tags:
    - ruby
    - gem
    - serverspec
  ignore_errors: yes
  shell: |
    source /etc/profile.d/anyenv.sh
    gem install serverspec -v '{{ serverspec_version }}'
    gem install specinfra -v '{{ specinfra_version }}'
