- name: nginx s3 upload conf file copy
  tags:
    - nginx
    - aws
    - s3
  template: >
    src=s3upload.conf.j2
    dest=/etc/nginx/conf.d/location/s3upload.conf
    mode=0755

- name: nginx s3 upload lua file copy
  tags:
    - nginx
    - aws
    - s3
  template: >
    src=rewrite_variables.lua.j2
    dest=/etc/nginx/conf.d/lua/rewrite_variables.lua
    mode=0755

