- name: archive packages install
  tags:
    - basic
    - basic/archive
  become: true
  ignore_errors: yes
  yum: >
    name={{ item }}
    state=latest
  with_items:
    - tar
    - zip
    - unzip
    - bzip2
