- name: ruby-build required library install
  tags:
    - ruby
    - ruby/build
  ignore_errors: yes
  yum: >
    name={{ item }}
    state=latest
  with_items:
    - readline-devel

- name: ruby-build clone
  tags:
    - ruby
    - ruby/build
  become: true
  git: >
    repo=https://github.com/rbenv/ruby-build.git
    dest={{ ruby_build_path }}

- name: ruby-build install
  tags:
    - ruby
    - ruby/build
  become: true
  shell: |
    cd {{ ruby_build_path }}
    ./install.sh
