- name: nginx conf files copy
  tags:
    - nginx
    - nginx/config/custom
  become: true
  template: >
    src={{ item.src }}
    dest={{ item.dest }}
    mode=0755
  with_items:
    - src: nginx.conf.j2
      dest: "{{ nginx__conf_dir }}/nginx.conf"
    - src: env.conf.j2
      dest: "{{ nginx__conf_dir }}/env.conf"
    - src: log.conf.j2
      dest: "{{ nginx__conf_dir }}/log.conf"
    - src: charset.conf.j2
      dest: "{{ nginx__conf_dir }}/charset.conf"
    - src: gzip.conf.j2
      dest: "{{ nginx__conf_dir }}/gzip.conf"
    - src: proxy.conf.j2
      dest: "{{ nginx__conf_dir }}/proxy.conf"
    - src: fastcgi_cache.conf.j2
      dest: "{{ nginx__conf_dir }}/fastcgi_cache.conf"

- name: nginx servers conf file touch
  tags:
    - nginx
    - nginx/config/custom
  become: true
  file: >
    path={{ nginx__conf_dir }}/servers.conf
    state=touch
    mode=0755
