- name: proj_name_app directory check
  shell: test -d /product/{{ item }} || mkdir -p /product/{{ item }}
  ignore_errors: true
  with_items: proj_name_app

- name: proj_name_app conf directory check
  shell: test -d /etc/httpd/conf.d/proj_name/ || mkdir -p /etc/httpd/conf.d/proj_name/
  ignore_errors: true

- name: copy Apache VirtualHost config file
  template: >
    src=virtualhost.conf.j2
    dest=/etc/httpd/conf.d/virtualhost.conf

- name: copy Apache proj_name app config file
  template: >
    src=proj_name_app.conf.j2
    dest=/etc/httpd/conf.d/proj_name/{{ item }}.conf
  with_items: proj_name_app

- name: copy Apache proj_name_admin config file
  template: >
    src=proj_name_admin.conf.j2
    dest=/etc/httpd/conf.d/proj_name/proj_name_admin.conf

- name: copy Apache proj_name_media config file
  template: >
    src=proj_name_media.conf.j2
    dest=/etc/httpd/conf.d/proj_name/proj_name_media.conf
