- name: copy nginx upstream conf
  tags:
    - nginx
    - nginx/config/upstream
  when: nginx_config_upstream__conf_name != ""
  template: >
    src=upstream.conf.j2
    dest=/etc/nginx/conf.d/upstream/{{ nginx_config_upstream__conf_name }}.conf
