- name: kibana install
  tags: 
    - elasticsearch
    - kibana
  ignore_errors: yes
  yum: >
    name=kibana
    state=latest

- name: kibana service enable
  tags:
    - kibana
  when: service_enable == 1
  service: >
    name=kibana
    enabled=yes

- name: kibana start
  tags:
    - kibana
  when: service_enable == 1
  service: >
    name=kibana
    state=restarted
