docker_image_registry_directory: /opt/docker/compose/registry
docker_image_registry_tag: 2
docker_image_registry_net_subnet: 172.30.255.0/24
docker_image_registry_net_gateway: 172.30.255.1
docker_image_registry_net_ip: 172.30.255.2
docker_image_registry_host: docker.registry
docker_image_registry_host_port: 5000
docker_image_registry_forward_port: 5000
docker_image_registry_container_name: docker_registry
docker_image_registry_env_file_directory: "{{ docker_image_registry_directory }}/.env"
docker_image_registry_s3_region: ap-northeast-1
docker_image_registry_delete_enabled: true
docker_image_registry_environment_settings: []

# Sample
#docker_image_registry_environment_settings: 
#  - environment: localhost
#    s3_accesskey: foo
#    s3_secretkey: bar
#    s3_bucket: devt_bucket
#  - environment: production
#    s3_accesskey: foo
#    s3_secretkey: bar
#    s3_bucket: prod_bucket
#    env_files:
#      - "{{ docker_image_registry_directory }}/common.env"
