dependencies:
  - role: common/fluentd/config/partial/ec2_metadata
    fluentd_config_partial_ec2_metadata_configs: "{{ fluentd_config_filter_ec2_metadata_configs }}"
  - role: common/fluentd/config/filter/base
    fluentd_config_filter_base_configs: "{{ fluentd_config_filter_ec2_metadata_configs }}"
    fluentd_config_filter_base_prefix: ec2_metadata
    when: is_ec2 == true
