- name: copy MySQL ini of supervisor
  tags:
    - mysql
    - supervisor
    - supervisor/middleware/mysql
  include_role:
    name: common/supervisor/config/program
  vars:
    supervisor__user: "" # root必須
    supervisor__config_program__name: mysql
    supervisor__config_program__user: mysql
    supervisor__config_program__command: /usr/bin/pidproxy {{ mysql__pidfile }} /usr/sbin/mysqld
    supervisor__config_program__stdout_logfile: "{{ supervisor__log_dir }}/mysql_stdout.log"
    supervisor__config_program__stderr_logfile: "{{ supervisor__log_dir }}/mysql_stderr.log"
