- name: install MySQL server
  tags:
    - mysql
    - supervisor
    - supervisor/middleware/mysql
  include_role:
    name: common/mysql/server/install

# include_roleでsupervisorインストールされる
- name: copy MySQL supervisor ini copy
  tags:
    - mysql
    - supervisor
    - supervisor/middleware/mysql
  include_role:
    name: common/supervisor/config/program
  vars:
    supervisor__user: "" # root必須
    supervisor__config_program__name: mysql
    supervisor__config_program__user: mysql
    supervisor__config_program__command: /usr/bin/pidproxy {{ mysql__pidfile }} /usr/sbin/mysqld
