- name: supervisor install
  tags:
    - supervisor
  become: true
  command: pip install supervisor

- name: create supervisor conf directory
  tags:
    - supervisor
  become: true
  file: >
    path={{ supervisor__conf_dir }}
    state=directory

- name: supervisor conf file copy
  tags:
    - supervisor
  become: true
  template: >
    src=supervisord.conf.j2
    dest=/etc/supervisord.conf
    mode=0755

- name: supervisor logrotate conf file copy
  tags:
    - supervisor
  become: true
  template: >
    src=logrotate.supervisor.j2
    dest=/etc/logrotate.d/supervisor
    mode=0755

- name: tmpfiles logrotate conf file copy
  tags:
    - supervisor
  become: true
  template: >
    src=tmpfiles.supervisor.conf.j2
    dest=/etc/tmpfiles.d/supervisor.conf
    mode=0755

- name: create supervisor log directory
  tags:
    - supervisor
  become: true
  file: >
    path={{ supervisor__log_dir }}
    state=directory
    owner={{ supervisor__user | default('root', true) }}

- name: create supervisor socket directory
  tags:
    - supervisor
  become: true
  file: >
    path={{ supervisor__socket_dir }}
    state=directory
    owner={{ supervisor__user | default('root', true) }}

- name: create supervisor exec shell directory
  tags:
    - supervisor
  become: true
  file: >
    path={{ supervisor__exec_shell_dir_dir }}
    state=directory
    owner={{ supervisor__user | default('root', true) }}
