- name: anyenv download
  tags:
    - anyenv
    - goenv
    - ndenv
    - phpenv
    - rbenv
  become: true
  git: >
    repo=https://github.com/riywo/anyenv
    dest={{ anyenv_path }}
     
- name: copy anyenv profile shell
  tags:
    - anyenv
    - goenv
    - ndenv
    - phpenv
    - rbenv
  become: true
  template: >
    src=anyenv.sh.j2
    dest=/etc/profile.d/proglang/anyenv.sh

- name: anyenv start
  tags:
    - anyenv
    - goenv
    - ndenv
    - phpenv
    - rbenv
  shell: |
    source /etc/profile
