- name: Golang installed check
  tags:
    - golang
  command: test -d {{ goenv_path }}/versions/{{ golang__version }}
  register: golang_directory_check
  failed_when: golang_directory_check.rc not in [0,1]

- name: Golang install
  tags:
    - golang
  when: golang_directory_check.rc != 0
  shell: |
    source /etc/profile.d/proglang.sh
    goenv install {{ golang__version }}

- name: Golang Version fix
  tags:
    - golang
  shell: |
    source /etc/profile.d/proglang.sh
    goenv global {{ golang__version }}
    goenv rehash
