- name: Golang installed check
  tags:
    - golang
  command: test -d {{ golang__path }}
  register: Register__golang_directory_check
  failed_when: Register__golang_directory_check.rc not in [0,1]

- name: Golang download
  tags:
   - golang
  become: true
  when: Register__golang_directory_check.rc != 0
  get_url: >
    url=https://golang.org/dl/go{{ golang__version }}.linux-amd64.tar.gz
    dest={{ golang__path }}.tar.gz

- name: Golang unarchive
  tags:
    - golang
  become: true
  when: Register__golang_directory_check.rc != 0
  shell: |
    cd /usr/local/
    tar xvzf {{ golang__path }}.tar.gz

- name: copy export gopath environment shell
  tags:
    - golang
  become: true
  template: >
    src=golang.sh.j2
    dest=/etc/profile.d/proglang/golang.sh
