- name: copy nginx ini of supervisor
  tags:
    - nginx
    - supervisor
    - supervisor/middleware/nginx
  include_role:
    name: common/supervisor/config/program
  vars:
    supervisor__config_program__name: nginx
    supervisor__config_program__command: "{{ supervisor__middleware_nginx__command }}"
    supervisor__config_program__stdout_logfile: "{{ supervisor__log_dir }}/nginx_stdout.log"
    supervisor__config_program__stderr_logfile: "{{ supervisor__log_dir }}/nginx_stderr.log"
