- name: install nginx
  tags:
    - nginx
    - supervisor
    - supervisor/middleware/nginx
  become: true
  when: nginx__install == true
  include_role:
    name: common/nginx/install

# include_roleでsupervisorインストールされる
- name: copy nginx supervisor ini copy
  tags:
    - nginx
    - supervisor
    - supervisor/middleware/nginx
  include_role:
    name: common/supervisor/config/program
  vars:
    supervisor__user: "" # root必須
    supervisor__config_program__name: nginx
    supervisor__config_program__command: "{{ supervisor__middleware_nginx__command }}"
