- name: simgle gem package regist 
  tags: 
    - ruby
    - ruby/gem/install
  when: "{{ gem__packages | length }} == 0 and gem__package != ''"
  set_fact:
    gem__packages:
      - name: "{{ gem__package }}"
        state: "{{ gem__state | default('present', true) }}"

- name: gem install
  tags: 
    - ruby
    - ruby/gem/install
  become: true
  environment:
    PATH: "{{ ruby__bin_path }}:{{ ansible_env.PATH }}"
  gem: > 
    name={{ item.name }}
    state={{ item.state | default('present', true) }}
    user_install=no
  with_items: "{{ gem__packages }}"
