- name: epel repository add RHEL6
  tags:
    - yum
    - epel
  ignore_errors: yes
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'
  command: rpm -ivh {{ epel_base_url }}{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/epel-release-{{ epel_minor_version_6 }}.noarch.rpm

- name: epel repository add RHEL7
  tags:
    - yum
    - epel
  ignore_errors: yes
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
  yum: >
    name=epel-release
    state=latest
