- hosts:
    - localhost
  roles:
    - { role: yum_repos } 
    - { role: basic_pkg } 
    - { role: basic_devel } 
    - { role: vim } 
    - { role: subversion } 
    - { role: git/install } 
    - { role: git/git_flow } 
    - { role: tmux } 
    - { role: sudoers } 
    - { role: mysql/install } 
    - { role: mysql/setting } 
    - { role: mysql/restart } 
    - { role: percona/repository } 
    - { role: percona/toolkit } 
    - { role: memcached }
    - { role: redis }
    - { role: java }
    - { role: anyenv/anyenv } 
    - { role: anyenv/ndenv } 
    - { role: anyenv/phpenv } 
    - { role: anyenv/rbenv } 
    - { role: anyenv/goenv } 
    - { role: php/install } 
    - { role: php/php-ext/igbinary } 
    - { role: php/php-ext/memcache } 
    - { role: php/php-ext/memcached } 
    - { role: php/php-ext/pecl_http } 
    - { role: php/php-ext/redis } 
    - { role: php/php-ext/swfed } 
    - { role: php/php-ext/xdebug } 
    - { role: php/php-ext/xhprof } 
    - { role: php/php-tools/phpunit } 
    - { role: php/php-tools/IO_Bit } 
    - { role: php/php-tools/IO_SWF } 
    - { role: php/phpmyadmin } 
    - { role: ruby/install } 
    - { role: ruby/gem/bundle } 
    - { role: ruby/gem/compass } 
    - { role: ruby/gem/serverspec } 
    - { role: node/install } 
    - { role: node/npm/canvas } 
    - { role: node/npm/node-gyp } 
    - { role: golang/install } 
    - { role: apache/install } 
    - { role: apache/php } 
    - { role: apache/phpmyadmin } 
    - { role: apache/restart } 
    - { role: fluentd/repo } 
    - { role: fluentd/install } 
    - { role: elasticsearch/repo } 
    - { role: elasticsearch/install } 
    - { role: elasticsearch/kibana } 
