- hosts:
    - localhost
  roles:
    - yum/repos 
    - yum/conf 
    - basic_pkg 
    - basic_devel 
    - vim 
    - subversion 
    - git/install 
    - git/git_flow 
    - tmux 
    - sudoers 
#    - gdal 
    - mysql/repo 
    - mysql/install 
    - mysql/setting 
    - mysql/restart 
    - percona/repository 
    - percona/toolkit 
    - memcached
    - redis
    - java
    - elasticsearch/repo 
    - elasticsearch/install 
    - elasticsearch/tools/stream2es
    - elasticsearch/plugins/elasticsearch-analysis-kuromoji
    - elasticsearch/plugins/elasticsearch-head
    - elasticsearch/kibana/repo
    - elasticsearch/kibana/install
    - anyenv/anyenv 
    - anyenv/ndenv 
    - anyenv/phpenv 
    - anyenv/rbenv 
    - anyenv/goenv 
    - php/install 
    - php/php-ext/igbinary 
    - php/php-ext/memcache 
    - php/php-ext/memcached 
    - php/php-ext/pecl_http 
    - php/php-ext/redis 
    - php/php-ext/xdebug 
    - php/php-ext/xhprof 
    - php/php-tools/phpunit 
    - php/php-tools/composer 
    - php/phpmyadmin 
    - ruby/install 
    - ruby/gem/bundle 
    - ruby/gem/compass 
    - ruby/gem/prmd 
    - ruby/gem/serverspec 
    - node/install 
#    - node/npm/canvas 
    - node/npm/node-gyp 
    - node/npm/node-inspector 
    - node/npm/vimdebug
    - node/package/hubot
    - golang/install 
    - lua/luajit 
#    - apache/install 
#    - apache/php 
#    - apache/phpmyadmin 
#    - apache/restart 
    - nginx/nginx-build 
    - nginx/install 
    - nginx/conf/elasticsearch
    - nginx/restart 
    - fluentd/repo 
    - fluentd/install 
