- name: MySQL 5.5 install
  when: mysql_version == 5.5
  yum: >
    name={{ item }}
    state=latest
    enablerepo=remi
  with_items:
    - mysql
    - mysql-server
    - mysql-devel
    - mysql-utilities
    - MySQL-python

- name: MySQL 5.6 install
  when: mysql_version == 5.6
  yum: >
    name={{ item }}
    state=latest
  with_items:
    - mysql
    - mysql-server
    - mysql-devel
    - mysql-utilities
    - MySQL-python

