- name: fluentd forward match config copy
  tags:
    - fluentd
    - fluentd/config/match/forward
  become: true
  template: >
    src=forward.conf.j2
    dest=/etc/td-agent/match.d/forward.conf
    mode=0755
