- name: fluentd elasticsearch match config copy
  tags:
    - fluentd
    - fluentd/config/match/elasticsearch
  become: true
  template: >
    src=elasticsearch.conf.j2
    dest=/etc/td-agent/match.d/elasticsearch.{{ item.tag_name }}.conf
    mode=0755
  with_items: "{{ fluentd_config_match_elasticsearch_configs }}"
