- name: fluentd elasticsearch plugin gem install
  tags:
    - fluentd
    - elasticsearch
  command: /opt/td-agent/embedded/bin/fluent-gem install fluent-plugin-elasticsearch

- name: fluentd elasticsearch match config copy
  tags:
    - fluentd
    - elasticsearch
  template: >
    src=elasticsearch.conf.j2
    dest=/etc/td-agent/match.d/{{ item.tag_name }}.conf
    mode=0755
  with_items: "{{ fluentd_elasticsearch_configs }}"
