- name: node.js installed check
  tags:
    - node
  command: test -d {{ ndenv_path }}/versions/{{ node_version }}
  register: nodejs_directory_check
  failed_when: nodejs_directory_check.rc not in [0,1]

- name: node.js install
  tags:
    - node
  when: nodejs_directory_check.rc != 0
  shell: |
    source /etc/profile.d/proglang.sh
    ndenv install {{ node_version }}

- name: node.js Version fix
  tags:
    - node
  shell: |
    source /etc/profile.d/proglang.sh
    ndenv global {{ node_version }}
    ndenv rehash
