- name: node install
  tags:
    - node
    - node/install
  become: true
  environment:
    PATH: "{{ node__bin_path }}:{{ ansible_env.PATH }}"
  command: node-build {{ node__version }} {{ node__path }}    

- name: copy export node environment shell
  tags:
    - node
    - node/install
  become: true
  when: node__bin_path != Default__node__bin_path
  template: >
    src=node.sh.j2
    dest=/etc/profile.d/proglang/node.sh
    mode=755
