- name: node.js install
  tags:
    - node
    - node/install
  shell: |
    node-build {{ node__version }} {{ node__path }}    

- name: copy export node environment shell
  tags:
    - node
    - node/install
  become: true
  template: >
    src=node.sh.j2
    dest=/etc/profile.d/proglang/node.sh
