- name: change supervisor nodaemon config
  tags:
    - supervisor
    - supervisor/daemon
  become: true
  lineinfile: >
    dest=/etc/supervisord.conf
    state=present
    backrefs=yes
    regexp='^nodaemon=false'
    line='nodaemon=true'
