- name: php depends library install
  tags:
    - php
  ignore_errors: yes
  yum: name={{ item }} state=latest
  with_items:
    - autoconf213
    - bison
    - httpd-devel
    - libxml2-devel
    - bzip2-devel
    - giflib-devel
    - libjpeg-turbo-devel
    - libpng-devel
    - freetype-devel
    - readline-devel
    - libxslt-devel
    - libtool-ltdl-devel
    - libtidy-devel

- name: php depends library install from epel repo by RedHat Version 6
  tags:
    - php
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'
  yum: name={{ item }} state=latest enablerepo=epel
  with_items:
    - libmcrypt-devel
    - re2c

- name: php depends library install from epel repo by RedHat Version 7
  tags:
    - php
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
  yum: name={{ item }} state=latest enablerepo=epel
  with_items:
    - libmcrypt-devel

- name: get apxs path
  tags:
    - php
  command: which apxs
  register: apxs_path
  failed_when: apxs_path.rc not in [0,1]

- name: copy php-build configure_options 
  tags:
    - php
  template: >
    src=default_configure_options.j2
    dest={{ php_build_dir }}/share/php-build/default_configure_options  

- name: php install
  tags:
    - php
  shell: |
    source /etc/profile.d/anyenv.sh
    phpenv install {{ php_version }}

- name: PHP Version fix
  tags:
    - php
  shell: |
    source /etc/profile.d/anyenv.sh
    phpenv global {{ php_version }}
    phpenv rehash

- name: change PHP date.timezone setting
  tags:
    - php
  command: >
    sed -i 's|^.*date.timezone.*|date.timezone="Asia/Tokyo"|g' {{ installed_php_dir }}/etc/php.ini
    removes={{ installed_php_dir }}/etc/php.ini

- name: change pear path
  tags:
    - php
  ignore_errors: yes
  shell: |
    rm -f /usr/share/pear
    ln -s {{ installed_php_dir }}/lib/php /usr/share/pear 
