- name: npm install
  tags:
    - node
    - npm
    - gulp
  environment:
    PATH: "{{ anyenv_path }}:{{ ansible_env.PATH }}"
  npm: >
    name=gulp
    state=latest
    global=yes

- name: active gulp 
  tags:
    - node
    - npm
    - gulp
  ignore_errors: yes
  shell: |
    source /etc/profile.d/proglang.sh
    ndenv rehash
