- name: regist systemd service
  tags: 
    - systemd
    - systemd/regist
  become: true
  when: systemd_regist__service_name != ""
  template: >
    src=service.j2
    dest=/etc/systemd/system/{{ systemd_regist__service_name }}.service
    mode=0644

- name: systemd daemon reload
  tags: 
    - systemd
    - systemd/regist
  become: true
  systemd:
    name: "{{ systemd_regist__service_name }}"
    daemon_reload: yes
