- name: goofys s3 bucket mount
  tags:
    - golang
    - golang/package/goofys
    - golang/package/goofys/mount
  when: goofys_s3_bucket != "" and goofys_s3_path != ""
  shell: |
    source /etc/profile.d/proglang.sh
    {{ gopath }}/bin/goofys {{ goofys_s3_bucket }} {{ goofys_s3_path }}

- name: add goofys uid mount option
  tags:
    - golang
    - golang/package/goofys
    - golang/package/goofys/mount
  when: goofys_s3_bucket != "" and goofys_s3_path != "" and goofys_fstab == true and goofys_mount_uid != ""
  set_fact:
    goofys_mount_option: "{{ goofys_mount_option }},--uid={{ goofys_mount_uid }}"

- name: add goofys gid mount option
  tags:
    - golang
    - golang/package/goofys
    - golang/package/goofys/mount
  when: goofys_s3_bucket != "" and goofys_s3_path != "" and goofys_fstab == true and goofys_mount_gid != ""
  set_fact:
    goofys_mount_option: "{{ goofys_mount_option }},--gid={{ goofys_mount_gid }}"

- name: add goofys s3 bucket mount setting
  tags:
    - golang
    - golang/package/goofys
    - golang/package/goofys/mount
  become: true
  when: goofys_s3_bucket != "" and goofys_s3_path != "" and goofys_fstab == true 
  mount: >
    src={{ goofys_gopath }}/bin/goofys#{{ goofys_s3_bucket }}
    name={{ goofys_s3_path }}
    state=present
    fstype=fuse
    opts={{ goofys_mount_option }}
