- name: create sub profile shell directory
  tags:
    - profile
    - anyenv
    - golang
  become: true
  file: >
    path=/etc/profile.d/proglang
    state=directory

- name: copy proglang profile shell
  tags:
    - profile
    - anyenv
    - golang
  become: true
  template: >
    src=proglang.sh.j2
    dest=/etc/profile.d/proglang.sh

