- name: docker install
  tags:
    - docker
  ignore_errors: yes
  yum: >
    name=docker-io
    state=latest

- name: docker enable RedHat6
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'
  tags:
    - docker
  command: chkconfig docker on

- name: docker enable RedHat7
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
  tags:
    - docker
  command: systemctl enable docker.service
