- name: elasticsearch install
  tags: 
    - elasticsearch
  ignore_errors: yes
  yum: >
    name=elasticsearch
    state=latest

- name: elasticsearch service enable 
  tags:
    - elasticsearch
  service: >
    name=elasticsearch
    enabled=yes

- name: elasticsearch start
  tags:
    - elasticsearch
  when: ansible_virtualization_type != 'docker'
  service: >
    name=elasticsearch
    state=started
