- name: fluentd tail source config copy
  tags:
    - fluentd
  template: >
    src=tail.conf.j2
    dest=/etc/td-agent/source.d/{{ item.tag_name }}.conf
    mode=0755
  with_items: "{{ fluentd_tail_configs }}"
