- name: Ruby install
  tags:
    - ruby
    - ruby/install
  become: true
  shell: |
    /usr/local/bin/ruby-build {{ ruby__version }} {{ ruby__path }}    

- name: copy export ruby environment shell
  tags:
    - ruby
    - ruby/install
  become: true
  when: ruby__bin_path != Default__ruby__bin_path
  template: >
    src=ruby.sh.j2
    dest=/etc/profile.d/proglang/ruby.sh
    mode=755
