- name: Ruby installed check
  tags:
    - ruby
    - ruby/install
  command: test -d {{ rbenv_path }}/versions/{{ ruby__version }}
  register: ruby_directory_check
  failed_when: ruby_directory_check.rc not in [0,1]

- name: Ruby install
  tags:
    - ruby
    - ruby/install
  become: true
  when: ruby_directory_check.rc != 0
  shell: |
    source /etc/profile.d/proglang.sh
    rbenv install {{ ruby__version }}

- name: Ruby Version fix
  tags:
    - ruby
    - ruby/install
  become: true
  shell: |
    source /etc/profile.d/proglang.sh
    rbenv global {{ ruby__version }}
    rbenv rehash
