- name: autoconf source file check
  tags:
    - basic_pkg
    - autoconf
  command: test -f {{ autoconf_path }}.tar.gz
  register: autoconf_source_check
  failed_when: autoconf_source_check.rc not in [0,1]

- name: autoconf download
  tags:
    - basic_pkg
    - autoconf
  become: true
  when: autoconf_source_check.rc != 0
  get_url: >
    url=http://ftp.gnu.org/gnu/autoconf/{{ autoconf_fullname }}.tar.gz
    dest={{ autoconf_path }}.tar.gz

- name: autoconf source directory check
  tags:
    - basic_pkg
    - autoconf
  command: test -d {{ autoconf_path }}
  register: autoconf_dir_check
  failed_when: autoconf_dir_check.rc not in [0,1]

- name: autoconf source directory remove
  tags:
    - basic_pkg
    - autoconf
  become: true
  when: autoconf_dir_check.rc == 0
  file: >
    path={{ autoconf_path }}
    state=absent

- name: autoconf unarchive
  tags:
    - basic_pkg
    - autoconf
  become: true
  shell: |
    cd /usr/local/src
    tar xvzf {{ autoconf_path }}.tar.gz

- name: autoconf install
  tags:
    - basic_pkg
    - autoconf
  become: true
  shell: |
    cd {{ autoconf_path }}
    ./configure
    make prefix=/usr
    make install prefix=/usr
