- name: compile packages install
  tags:
    - basic
    - basic/compile
  become: true
  ignore_errors: yes
  yum: >
    name={{ item }}
    state=latest
  with_items:
    - gcc
    - gcc-c++
    - make
    - libtool

- include: autoconf.yml 
- include: automake.yml 
