- name: Golang installed check
  tags:
    - golang
  command: test -d {{ golang_path }}
  register: golang_directory_check
  failed_when: golang_directory_check.rc not in [0,1]

- name: Golang download
  tags:
   - git
  when: golang_directory_check.rc != 0
  get_url: >
    url=https://golang.org/dl/go{{ golang_version }}.linux-amd64.tar.gz
    dest={{ golang_path }}.tar.gz

- name: Golang unarchive
  tags:
    - golang
  when: golang_directory_check.rc != 0
  shell: |
    cd /usr/local/
    tar xvzf {{ golang_path }}.tar.gz

- name: copy export gopath environment shell
  tags:
    - golang
  template: >
    src=golang.sh.j2
    dest=/etc/profile.d/proglang/golang.sh
